// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: test

#ifndef _UI_COMP_SLIDER2_H
#define _UI_COMP_SLIDER2_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Slider2
#define UI_COMP_SLIDER2_SLIDER2 0
#define _UI_COMP_SLIDER2_NUM 1
lv_obj_t * ui_Slider2_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
